# Facebook Messenger Configuration

# Browser Configuration
browser:
  headless: true
  window_size: "1920,1080"
  user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
  page_load_timeout: 30
  implicit_wait: 10
  enable_stealth: true

# Proxy Configuration  
proxy:
  enabled: true
  provider: "iproyal"
  sticky_sessions: true
  connection_timeout: 15

# Facebook Configuration
facebook:
  login_url: "https://www.facebook.com/login"
  max_login_attempts: 3
  session_refresh_hours: 12

# Messaging Configuration
messaging:
  max_messages_per_hour: 5
  delay_between_messages: 300  # 5 minutes
  templates:
    - "Hi! Is your {camera_name} still available?"
    - "Hello! I'm interested in the {camera_name}. Could you tell me more about its condition?"
    - "Hi there! What's the condition of your {camera_name}?"

# Paths
paths:
  cookies_dir: "/app/cookies"
  logs_dir: "/app/logs"
  screenshots_dir: "/app/screenshots"

# Logging
logging:
  level: "INFO"
  save_screenshots_on_error: true