version: '3.8'

services:
  # Chatterbot API - receives leads
  chatterbot-api:
    build: ./facebook-messenger
    container_name: chatterbot-api
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_AUTH_ENABLED=false  # Disabled on private network
    ports:
      - "5000:5000"
    command: gunicorn -w 2 -b 0.0.0.0:5000 src.api.server:app
    networks:
      - aetos

  # Chatterbot Worker - sends messages (TODO: implement)
  chatterbot-worker:
    build: ./facebook-messenger
    container_name: chatterbot-worker
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - messenger-cookies:/app/cookies
      - messenger-logs:/app/logs
    command: python src/main.py
    networks:
      - aetos
    depends_on:
      - chatterbot-api

  # Scraper - finds cameras, sends to chatterbot
  scraper:
    build: .
    container_name: scraper
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CHATTERBOT_ENABLED=true
      - CHATTERBOT_URL=http://chatterbot-api:5000
    volumes:
      - scraper-cookies:/app/cookies
      - scraper-logs:/app/logs
    command: python src/main.py
    networks:
      - aetos

volumes:
  scraper-cookies:
  scraper-logs:
  messenger-cookies:
  messenger-logs:

networks:
  aetos:
    driver: bridge

# Azure VM Deployment:
# 1. Set DATABASE_URL in .env
# 2. Run: docker-compose up -d
# 3. Containers communicate on private network (no auth needed)